### ISSUE TITLE
Threading exceptions in Python

### ISSUE THREAD

**Issue by Cyber-m0nk** [yoelbassin/ARP-spoofing-Detection#2]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "arpdetadv.py", line 24, in sniff_replays
    sniff(filter='arp', lfilter=incoming_reply, prn=check_arp_header, iface=conf.iface)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 972, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 842, in _run
    *arg, **karg)] = iface
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 475, in __init__
    attach_filter(self.ins, filter, iface)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 160, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/common.py", line 165, in compile_filter
    raise Scapy_Exception("tcpdump is not available. Cannot use filter !")
Scapy_Exception: tcpdump is not available. Cannot use filter !

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "arpdetadv.py", line 16, in sniff_requests
    sniff(filter='arp', lfilter=outgoing_req, prn=add_req, iface=conf.iface)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 972, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 842, in _run
    *arg, **karg)] = iface
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 475, in __init__
    attach_filter(self.ins, filter, iface)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 160, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/common.py", line 165, in compile_filter
    raise Scapy_Exception("tcpdump is not available. Cannot use filter !")
Scapy_Exception: tcpdump is not available. Cannot use filter !

**Comment by yoelbassin** [comment]
Hey!
Thanks for reaching out.
Do you have tcpdump installed on the machine?
Try using `tcpdump -v` in the terminal in order to check this

**Comment by Cyber-m0nk** [comment]
hey, thanks for your quick reply. yes tcpdump latest version 4.99.0.-2 is installed on  my machine. But still I am getting threading exception

previously I tried on kali Linux and now even I tried on ubuntu, again same threading exception.


Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "arpdect.py", line 16, in sniff_requests
    sniff(filter='arp', lfilter=outgoing_req, prn=add_req, iface=conf.iface)
  File "/home/seed/.local/lib/python2.7/site-packages/scapy/sendrecv.py", line 731, in sniff
    *arg, **karg)] = iface
  File "/home/seed/.local/lib/python2.7/site-packages/scapy/arch/linux.py", line 567, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 1] Operation not permitted

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "arpdect.py", line 24, in sniff_replays
    sniff(filter='arp', lfilter=incoming_reply, prn=check_arp_header, iface=conf.iface)
  File "/home/seed/.local/lib/python2.7/site-packages/scapy/sendrecv.py", line 731, in sniff
    *arg, **karg)] = iface
  File "/home/seed/.local/lib/python2.7/site-packages/scapy/arch/linux.py", line 567, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 1] Operation not permitted

**Comment by yoelbassin** [comment]
Hey, have you tried running it using python3 with the latest version of Scapy?
And on what version of Kali have you tried it?
